//
// Generated by JTB 1.3.2
//

package parser.minijava.ast;

import parser.minijava.visitor.GJNoArguVisitor;
import parser.minijava.visitor.GJVisitor;
import parser.minijava.visitor.GJVoidVisitor;
import parser.minijava.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> <CLASS>
 * f1 -> Identifier()
 * f2 -> <EXTENDS>
 * f3 -> Identifier()
 * f4 -> <LBRACE>
 * f5 -> ( Comment() )*
 * f6 -> ( VarDeclarationUnordered() )*
 * f7 -> ( MethodDeclarationUnordered() )*
 * f8 -> <RBRACE>
 */
public class ClassExtendsDeclaration implements Node {
    public NodeToken f0;
    public Identifier f1;
    public NodeToken f2;
    public Identifier f3;
    public NodeToken f4;
    public NodeListOptional f5;
    public NodeListOptional f6;
    public NodeListOptional f7;
    public NodeToken f8;

    public ClassExtendsDeclaration(NodeToken n0, Identifier n1, NodeToken n2, Identifier n3, NodeToken n4, NodeListOptional n5, NodeListOptional n6, NodeListOptional n7, NodeToken n8) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
        f3 = n3;
        f4 = n4;
        f5 = n5;
        f6 = n6;
        f7 = n7;
        f8 = n8;
    }

    public ClassExtendsDeclaration(Identifier n0, Identifier n1, NodeListOptional n2, NodeListOptional n3, NodeListOptional n4) {
        f0 = new NodeToken("class");
        f1 = n0;
        f2 = new NodeToken("extends");
        f3 = n1;
        f4 = new NodeToken("{");
        f5 = n2;
        f6 = n3;
        f7 = n4;
        f8 = new NodeToken("}");
    }

    public void accept(Visitor v) {
        v.visit(this);
    }

    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

