//
// Generated by JTB 1.3.2
//

package minijava.visitor;

import minijava.ast.AllocationExpression;
import minijava.ast.AndExpression;
import minijava.ast.ArrayAllocationExpression;
import minijava.ast.ArrayAssignmentStatement;
import minijava.ast.ArrayLength;
import minijava.ast.ArrayLookup;
import minijava.ast.ArrayType;
import minijava.ast.AssignmentStatement;
import minijava.ast.Block;
import minijava.ast.BooleanType;
import minijava.ast.BracketExpression;
import minijava.ast.ClassDeclaration;
import minijava.ast.ClassExtendsDeclaration;
import minijava.ast.Comment;
import minijava.ast.CompareExpression;
import minijava.ast.Expression;
import minijava.ast.ExpressionList;
import minijava.ast.ExpressionRest;
import minijava.ast.FalseLiteral;
import minijava.ast.FormalParameter;
import minijava.ast.FormalParameterList;
import minijava.ast.FormalParameterRest;
import minijava.ast.Goal;
import minijava.ast.Identifier;
import minijava.ast.IfStatement;
import minijava.ast.IntegerLiteral;
import minijava.ast.IntegerType;
import minijava.ast.MainClass;
import minijava.ast.MessageSend;
import minijava.ast.MethodDeclarationUnordered;
import minijava.ast.MinusExpression;
import minijava.ast.NodeList;
import minijava.ast.NodeListOptional;
import minijava.ast.NodeOptional;
import minijava.ast.NodeSequence;
import minijava.ast.NodeToken;
import minijava.ast.NotExpression;
import minijava.ast.PlusExpression;
import minijava.ast.PrimaryExpression;
import minijava.ast.PrintStatement;
import minijava.ast.Statement;
import minijava.ast.ThisExpression;
import minijava.ast.TimesExpression;
import minijava.ast.TrueLiteral;
import minijava.ast.Type;
import minijava.ast.TypeDeclarationUnordered;
import minijava.ast.VarDeclarationUnordered;
import minijava.ast.WhileStatement;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

    //
    // GJ Auto class visitors with no argument
    //

    public R visit(NodeList n);

    public R visit(NodeListOptional n);

    public R visit(NodeOptional n);

    public R visit(NodeSequence n);

    public R visit(NodeToken n);

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> MainClass() f1 -> ( TypeDeclarationUnordered() )* f2 -> <EOF>
     */
    public R visit(Goal n);

    /**
     * f0 -> "class" f1 -> Identifier() f2 -> "{" f3 -> "public" f4 -> "static" f5 -> "void" f6 ->
     * "main" f7 -> "(" f8 -> "String" f9 -> "[" f10 -> "]" f11 -> Identifier() f12 -> ")" f13 ->
     * "{" f14 -> PrintStatement() f15 -> "}" f16 -> "}"
     */
    public R visit(MainClass n);

    /**
     * f0 -> ClassDeclaration() | ClassExtendsDeclaration()
     */
    public R visit(TypeDeclarationUnordered n);

    /**
     * f0 -> "class" f1 -> Identifier() f2 -> "{" f3 -> ( Comment() )* f4 -> (
     * VarDeclarationUnordered() )* f5 -> ( MethodDeclarationUnordered() )* f6 -> "}"
     */
    public R visit(ClassDeclaration n);

    /**
     * f0 -> "class" f1 -> Identifier() f2 -> "extends" f3 -> Identifier() f4 -> "{" f5 -> (
     * Comment() )* f6 -> ( VarDeclarationUnordered() )* f7 -> ( MethodDeclarationUnordered() )* f8
     * -> "}"
     */
    public R visit(ClassExtendsDeclaration n);

    /**
     * f0 -> Type() f1 -> Identifier() f2 -> ";"
     */
    public R visit(VarDeclarationUnordered n);

    /**
     * f0 -> "public" f1 -> Type() f2 -> Identifier() f3 -> "(" f4 -> ( FormalParameterList() )? f5
     * -> ")" f6 -> "{" f7 -> ( Comment() )* f8 -> ( VarDeclarationUnordered() )* f9 -> (
     * Statement() )* f10 -> "return" f11 -> Expression() f12 -> ";" f13 -> "}"
     */
    public R visit(MethodDeclarationUnordered n);

    /**
     * f0 -> FormalParameter() f1 -> ( FormalParameterRest() )*
     */
    public R visit(FormalParameterList n);

    /**
     * f0 -> Type() f1 -> Identifier()
     */
    public R visit(FormalParameter n);

    /**
     * f0 -> "," f1 -> FormalParameter()
     */
    public R visit(FormalParameterRest n);

    /**
     * f0 -> ArrayType() | BooleanType() | IntegerType() | Identifier()
     */
    public R visit(Type n);

    /**
     * f0 -> "int" f1 -> "[" f2 -> "]"
     */
    public R visit(ArrayType n);

    /**
     * f0 -> "boolean"
     */
    public R visit(BooleanType n);

    /**
     * f0 -> "int"
     */
    public R visit(IntegerType n);

    /**
     * f0 -> Block() | AssignmentStatement() | ArrayAssignmentStatement() | IfStatement() |
     * WhileStatement() | PrintStatement()
     */
    public R visit(Statement n);

    /**
     * f0 -> "{" f1 -> ( Statement() )* f2 -> "}"
     */
    public R visit(Block n);

    /**
     * f0 -> Identifier() f1 -> "=" f2 -> Expression() f3 -> ";"
     */
    public R visit(AssignmentStatement n);

    /**
     * f0 -> Identifier() f1 -> "[" f2 -> Expression() f3 -> "]" f4 -> "=" f5 -> Expression() f6 ->
     * ";"
     */
    public R visit(ArrayAssignmentStatement n);

    /**
     * f0 -> "if" f1 -> "(" f2 -> Expression() f3 -> ")" f4 -> Statement() f5 -> "else" f6 ->
     * Statement()
     */
    public R visit(IfStatement n);

    /**
     * f0 -> "while" f1 -> "(" f2 -> Expression() f3 -> ")" f4 -> Statement()
     */
    public R visit(WhileStatement n);

    /**
     * f0 -> "System.out.println" f1 -> "(" f2 -> Expression() f3 -> ")" f4 -> ";"
     */
    public R visit(PrintStatement n);

    /**
     * f0 -> AndExpression() | CompareExpression() | PlusExpression() | MinusExpression() |
     * TimesExpression() | ArrayLookup() | ArrayLength() | MessageSend() | PrimaryExpression()
     */
    public R visit(Expression n);

    /**
     * f0 -> PrimaryExpression() f1 -> "&&" f2 -> PrimaryExpression()
     */
    public R visit(AndExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> "<" f2 -> PrimaryExpression()
     */
    public R visit(CompareExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> "+" f2 -> PrimaryExpression()
     */
    public R visit(PlusExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> "-" f2 -> PrimaryExpression()
     */
    public R visit(MinusExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> "*" f2 -> PrimaryExpression()
     */
    public R visit(TimesExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> "[" f2 -> PrimaryExpression() f3 -> "]"
     */
    public R visit(ArrayLookup n);

    /**
     * f0 -> PrimaryExpression() f1 -> "." f2 -> "length"
     */
    public R visit(ArrayLength n);

    /**
     * f0 -> PrimaryExpression() f1 -> "." f2 -> Identifier() f3 -> "(" f4 -> ( ExpressionList() )?
     * f5 -> ")"
     */
    public R visit(MessageSend n);

    /**
     * f0 -> Expression() f1 -> ( ExpressionRest() )*
     */
    public R visit(ExpressionList n);

    /**
     * f0 -> "," f1 -> Expression()
     */
    public R visit(ExpressionRest n);

    /**
     * f0 -> IntegerLiteral() | TrueLiteral() | FalseLiteral() | Identifier() | ThisExpression() |
     * ArrayAllocationExpression() | AllocationExpression() | NotExpression() | BracketExpression()
     */
    public R visit(PrimaryExpression n);

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    public R visit(IntegerLiteral n);

    /**
     * f0 -> "true"
     */
    public R visit(TrueLiteral n);

    /**
     * f0 -> "false"
     */
    public R visit(FalseLiteral n);

    /**
     * f0 -> <IDENTIFIER>
     */
    public R visit(Identifier n);

    /**
     * f0 -> "this"
     */
    public R visit(ThisExpression n);

    /**
     * f0 -> "new" f1 -> "int" f2 -> "[" f3 -> Expression() f4 -> "]"
     */
    public R visit(ArrayAllocationExpression n);

    /**
     * f0 -> "new" f1 -> Identifier() f2 -> "(" f3 -> ")"
     */
    public R visit(AllocationExpression n);

    /**
     * f0 -> "!" f1 -> Expression()
     */
    public R visit(NotExpression n);

    /**
     * f0 -> "(" f1 -> Expression() f2 -> ")"
     */
    public R visit(BracketExpression n);

    /**
     * f0 -> <SINGLE_LINE_COMMENT> | <FORMAL_COMMENT> | <MULTI_LINE_COMMENT>
     */
    public R visit(Comment n);

}

