//
// Generated by JTB 1.3.2
//

package minijava.visitor;

import minijava.ast.AllocationExpression;
import minijava.ast.AndExpression;
import minijava.ast.ArrayAllocationExpression;
import minijava.ast.ArrayAssignmentStatement;
import minijava.ast.ArrayLength;
import minijava.ast.ArrayLookup;
import minijava.ast.ArrayType;
import minijava.ast.AssignmentStatement;
import minijava.ast.Block;
import minijava.ast.BooleanType;
import minijava.ast.BranchStatement;
import minijava.ast.ClassDeclaration;
import minijava.ast.ClassExtendsDeclaration;
import minijava.ast.Comment;
import minijava.ast.CompareExpression;
import minijava.ast.Expression;
import minijava.ast.ExpressionList;
import minijava.ast.ExpressionRest;
import minijava.ast.FalseLiteral;
import minijava.ast.FormalParameter;
import minijava.ast.FormalParameterList;
import minijava.ast.FormalParameterRest;
import minijava.ast.Goal;
import minijava.ast.Identifier;
import minijava.ast.IntegerLiteral;
import minijava.ast.IntegerType;
import minijava.ast.MainClass;
import minijava.ast.MessageSend;
import minijava.ast.MethodDeclarationUnordered;
import minijava.ast.MinusExpression;
import minijava.ast.NodeList;
import minijava.ast.NodeListOptional;
import minijava.ast.NodeOptional;
import minijava.ast.NodeSequence;
import minijava.ast.NodeToken;
import minijava.ast.NotExpression;
import minijava.ast.ParanthesisExpression;
import minijava.ast.PlusExpression;
import minijava.ast.PrimaryExpression;
import minijava.ast.PrintStatement;
import minijava.ast.Statement;
import minijava.ast.ThisExpression;
import minijava.ast.TimesExpression;
import minijava.ast.TrueLiteral;
import minijava.ast.Type;
import minijava.ast.TypeDeclarationUnordered;
import minijava.ast.VarDeclarationUnordered;
import minijava.ast.WhileStatement;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

    //
    // void Auto class visitors
    //

    public void visit(NodeList n);

    public void visit(NodeListOptional n);

    public void visit(NodeOptional n);

    public void visit(NodeSequence n);

    public void visit(NodeToken n);

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> MainClass() f1 -> ( TypeDeclarationUnordered() )* f2 -> <EOF>
     */
    public void visit(Goal n);

    /**
     * f0 -> <CLASS> f1 -> Identifier() f2 -> <LBRACE> f3 -> <PUBLIC> f4 -> <STATIC> f5 -> <VOID> f6
     * -> <MAIN> f7 -> <LPAREN> f8 -> <STRING> f9 -> <LSQPAREN> f10 -> <RSQPAREN> f11 ->
     * Identifier() f12 -> <RPAREN> f13 -> <LBRACE> f14 -> PrintStatement() f15 -> <RBRACE> f16 ->
     * <RBRACE>
     */
    public void visit(MainClass n);

    /**
     * f0 -> ClassDeclaration() | ClassExtendsDeclaration()
     */
    public void visit(TypeDeclarationUnordered n);

    /**
     * f0 -> <CLASS> f1 -> Identifier() f2 -> <LBRACE> f3 -> ( Comment() )* f4 -> (
     * VarDeclarationUnordered() )* f5 -> ( MethodDeclarationUnordered() )* f6 -> <RBRACE>
     */
    public void visit(ClassDeclaration n);

    /**
     * f0 -> <CLASS> f1 -> Identifier() f2 -> <EXTENDS> f3 -> Identifier() f4 -> <LBRACE> f5 -> (
     * Comment() )* f6 -> ( VarDeclarationUnordered() )* f7 -> ( MethodDeclarationUnordered() )* f8
     * -> <RBRACE>
     */
    public void visit(ClassExtendsDeclaration n);

    /**
     * f0 -> Type() f1 -> Identifier() f2 -> <SEMICOLON>
     */
    public void visit(VarDeclarationUnordered n);

    /**
     * f0 -> <PUBLIC> f1 -> Type() f2 -> Identifier() f3 -> <LPAREN> f4 -> ( FormalParameterList()
     * )? f5 -> <RPAREN> f6 -> <LBRACE> f7 -> ( Comment() )* f8 -> ( VarDeclarationUnordered() )* f9
     * -> ( Statement() )* f10 -> <RETURN> f11 -> Expression() f12 -> <SEMICOLON> f13 -> <RBRACE>
     */
    public void visit(MethodDeclarationUnordered n);

    /**
     * f0 -> FormalParameter() f1 -> ( FormalParameterRest() )*
     */
    public void visit(FormalParameterList n);

    /**
     * f0 -> Type() f1 -> Identifier()
     */
    public void visit(FormalParameter n);

    /**
     * f0 -> <COMMA> f1 -> FormalParameter()
     */
    public void visit(FormalParameterRest n);

    /**
     * f0 -> ArrayType() | BooleanType() | IntegerType() | Identifier()
     */
    public void visit(Type n);

    /**
     * f0 -> <INTEGER> f1 -> <LSQPAREN> f2 -> <RSQPAREN>
     */
    public void visit(ArrayType n);

    /**
     * f0 -> <BOOLEAN>
     */
    public void visit(BooleanType n);

    /**
     * f0 -> <INTEGER>
     */
    public void visit(IntegerType n);

    /**
     * f0 -> Block() | AssignmentStatement() | ArrayAssignmentStatement() | BranchStatement() |
     * WhileStatement() | PrintStatement()
     */
    public void visit(Statement n);

    /**
     * f0 -> <LBRACE> f1 -> ( Statement() )* f2 -> <RBRACE>
     */
    public void visit(Block n);

    /**
     * f0 -> Identifier() f1 -> <ASSIGN> f2 -> Expression() f3 -> <SEMICOLON>
     */
    public void visit(AssignmentStatement n);

    /**
     * f0 -> Identifier() f1 -> <LSQPAREN> f2 -> Expression() f3 -> <RSQPAREN> f4 -> <ASSIGN> f5 ->
     * Expression() f6 -> <SEMICOLON>
     */
    public void visit(ArrayAssignmentStatement n);

    /**
     * f0 -> <IF> <LPAREN> Expression() <RPAREN> <LBRACE> Statement() <RBRACE> | <ELSE_IF> <LPAREN>
     * Expression() <RPAREN> <LBRACE> Statement() <RBRACE> | <ELSE> <LBRACE> Statement() <RBRACE>
     */
    public void visit(BranchStatement n);

    /**
     * f0 -> <WHILE> f1 -> <LPAREN> f2 -> Expression() f3 -> <RPAREN> f4 -> Statement()
     */
    public void visit(WhileStatement n);

    /**
     * f0 -> <PRINT> f1 -> <LPAREN> f2 -> Expression() f3 -> <RPAREN> f4 -> <SEMICOLON>
     */
    public void visit(PrintStatement n);

    /**
     * f0 -> AndExpression() | CompareExpression() | PlusExpression() | MinusExpression() |
     * TimesExpression() | ArrayLookup() | ArrayLength() | MessageSend() | PrimaryExpression()
     */
    public void visit(Expression n);

    /**
     * f0 -> PrimaryExpression() f1 -> <AND> f2 -> PrimaryExpression()
     */
    public void visit(AndExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> <LT> f2 -> PrimaryExpression()
     */
    public void visit(CompareExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> <PLUS> f2 -> PrimaryExpression()
     */
    public void visit(PlusExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> <MINUS> f2 -> PrimaryExpression()
     */
    public void visit(MinusExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> <MULTIPLY> f2 -> PrimaryExpression()
     */
    public void visit(TimesExpression n);

    /**
     * f0 -> PrimaryExpression() f1 -> <LSQPAREN> f2 -> PrimaryExpression() f3 -> <RSQPAREN>
     */
    public void visit(ArrayLookup n);

    /**
     * f0 -> PrimaryExpression() f1 -> <DOT> f2 -> <LENGTH>
     */
    public void visit(ArrayLength n);

    /**
     * f0 -> PrimaryExpression() f1 -> <DOT> f2 -> Identifier() f3 -> <LPAREN> f4 -> (
     * ExpressionList() )? f5 -> <RPAREN>
     */
    public void visit(MessageSend n);

    /**
     * f0 -> Expression() f1 -> ( ExpressionRest() )*
     */
    public void visit(ExpressionList n);

    /**
     * f0 -> <COMMA> f1 -> Expression()
     */
    public void visit(ExpressionRest n);

    /**
     * f0 -> IntegerLiteral() | TrueLiteral() | FalseLiteral() | Identifier() | ThisExpression() |
     * ArrayAllocationExpression() | AllocationExpression() | NotExpression() |
     * ParanthesisExpression()
     */
    public void visit(PrimaryExpression n);

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    public void visit(IntegerLiteral n);

    /**
     * f0 -> <TRUE>
     */
    public void visit(TrueLiteral n);

    /**
     * f0 -> <FALSE>
     */
    public void visit(FalseLiteral n);

    /**
     * f0 -> <IDENTIFIER>
     */
    public void visit(Identifier n);

    /**
     * f0 -> <THIS>
     */
    public void visit(ThisExpression n);

    /**
     * f0 -> <NEW> f1 -> <INTEGER> f2 -> <LSQPAREN> f3 -> Expression() f4 -> <RSQPAREN>
     */
    public void visit(ArrayAllocationExpression n);

    /**
     * f0 -> <NEW> f1 -> Identifier() f2 -> <LPAREN> f3 -> <RPAREN>
     */
    public void visit(AllocationExpression n);

    /**
     * f0 -> <NOT> f1 -> Expression()
     */
    public void visit(NotExpression n);

    /**
     * f0 -> <LPAREN> f1 -> Expression() f2 -> <RPAREN>
     */
    public void visit(ParanthesisExpression n);

    /**
     * f0 -> <SINGLE_LINE_COMMENT> | <FORMAL_COMMENT> | <MULTI_LINE_COMMENT>
     */
    public void visit(Comment n);

}

