/* Generated By:JavaCC: Do not edit this line. BSParserConstants.java */
package parser.bioscript.parser;


/**
 * Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BSParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int MIX = 6;
    /**
     * RegularExpression Id.
     */
    int SPLIT = 7;
    /**
     * RegularExpression Id.
     */
    int DRAIN = 8;
    /**
     * RegularExpression Id.
     */
    int HEAT = 9;
    /**
     * RegularExpression Id.
     */
    int FOR = 10;
    /**
     * RegularExpression Id.
     */
    int AT = 11;
    /**
     * RegularExpression Id.
     */
    int DETECT = 12;
    /**
     * RegularExpression Id.
     */
    int REPEAT = 13;
    /**
     * RegularExpression Id.
     */
    int IF = 14;
    /**
     * RegularExpression Id.
     */
    int ELSE_IF = 15;
    /**
     * RegularExpression Id.
     */
    int ELSE = 16;
    /**
     * RegularExpression Id.
     */
    int STATIONARY = 17;
    /**
     * RegularExpression Id.
     */
    int MANIFEST = 18;
    /**
     * RegularExpression Id.
     */
    int TIMES = 19;
    /**
     * RegularExpression Id.
     */
    int WITH = 20;
    /**
     * RegularExpression Id.
     */
    int ON = 21;
    /**
     * RegularExpression Id.
     */
    int INTO = 22;
    /**
     * RegularExpression Id.
     */
    int SOMETHING = 23;
    /**
     * RegularExpression Id.
     */
    int LPAREN = 24;
    /**
     * RegularExpression Id.
     */
    int RPAREN = 25;
    /**
     * RegularExpression Id.
     */
    int LBRACKET = 26;
    /**
     * RegularExpression Id.
     */
    int RBRACKET = 27;
    /**
     * RegularExpression Id.
     */
    int LBRACE = 28;
    /**
     * RegularExpression Id.
     */
    int RBRACE = 29;
    /**
     * RegularExpression Id.
     */
    int DOT = 30;
    /**
     * RegularExpression Id.
     */
    int ADD = 31;
    /**
     * RegularExpression Id.
     */
    int AND = 32;
    /**
     * RegularExpression Id.
     */
    int ASSIGN = 33;
    /**
     * RegularExpression Id.
     */
    int BANG = 34;
    /**
     * RegularExpression Id.
     */
    int NOTEQUAL = 35;
    /**
     * RegularExpression Id.
     */
    int LESSTHAN = 36;
    /**
     * RegularExpression Id.
     */
    int LESSTHANEQUAL = 37;
    /**
     * RegularExpression Id.
     */
    int GREATERTHAN = 38;
    /**
     * RegularExpression Id.
     */
    int GREATERTHANEQUAL = 39;
    /**
     * RegularExpression Id.
     */
    int EQUALITY = 40;
    /**
     * RegularExpression Id.
     */
    int MINUS = 41;
    /**
     * RegularExpression Id.
     */
    int MULTIPLY = 42;
    /**
     * RegularExpression Id.
     */
    int OR = 43;
    /**
     * RegularExpression Id.
     */
    int INSTRUCTIONS = 44;
    /**
     * RegularExpression Id.
     */
    int TRUE = 45;
    /**
     * RegularExpression Id.
     */
    int FALSE = 46;
    /**
     * RegularExpression Id.
     */
    int INT_SCALAR = 47;
    /**
     * RegularExpression Id.
     */
    int INTEGER_LITERAL = 48;
    /**
     * RegularExpression Id.
     */
    int IDENTIFIER = 49;
    /**
     * RegularExpression Id.
     */
    int LETTER = 50;
    /**
     * RegularExpression Id.
     */
    int DIGIT = 51;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "\"mix\"",
            "\"split\"",
            "\"drain\"",
            "\"heat\"",
            "\"for\"",
            "\"at\"",
            "\"detect\"",
            "\"repeat\"",
            "\"if\"",
            "\"else if\"",
            "\"else\"",
            "\"stationary\"",
            "\"manifest\"",
            "\"times\"",
            "\"with\"",
            "\"on\"",
            "\"into\"",
            "\"something\"",
            "\"(\"",
            "\")\"",
            "\"[\"",
            "\"]\"",
            "\"{\"",
            "\"}\"",
            "\".\"",
            "\"+\"",
            "\"&&\"",
            "\"=\"",
            "\"!\"",
            "\"!=\"",
            "\"<\"",
            "\"<=\"",
            "\">\"",
            "\">=\"",
            "\"==\"",
            "\"-\"",
            "\"*\"",
            "\"||\"",
            "\"instructions\"",
            "\"true\"",
            "\"false\"",
            "<INT_SCALAR>",
            "<INTEGER_LITERAL>",
            "<IDENTIFIER>",
            "<LETTER>",
            "<DIGIT>",
    };

}
