//
// Generated by JTB 1.3.2
//

package parser.bioscript.visitor;

import java.util.Enumeration;

import parser.bioscript.ast.AndExpression;
import parser.bioscript.ast.AssignmentStatement;
import parser.bioscript.ast.BranchStatement;
import parser.bioscript.ast.DetectStatement;
import parser.bioscript.ast.DrainStatement;
import parser.bioscript.ast.EqualityExpression;
import parser.bioscript.ast.Expression;
import parser.bioscript.ast.FalseLiteral;
import parser.bioscript.ast.GreaterThanEqualExpression;
import parser.bioscript.ast.GreaterThanExpression;
import parser.bioscript.ast.HeatStatement;
import parser.bioscript.ast.Identifier;
import parser.bioscript.ast.Instruction;
import parser.bioscript.ast.IntegerLiteral;
import parser.bioscript.ast.LessThanEqualExpression;
import parser.bioscript.ast.LessThanExpression;
import parser.bioscript.ast.Manifest;
import parser.bioscript.ast.MinusExpression;
import parser.bioscript.ast.MixStatement;
import parser.bioscript.ast.Node;
import parser.bioscript.ast.NodeList;
import parser.bioscript.ast.NodeListOptional;
import parser.bioscript.ast.NodeOptional;
import parser.bioscript.ast.NodeSequence;
import parser.bioscript.ast.NodeToken;
import parser.bioscript.ast.NotEqualExpression;
import parser.bioscript.ast.NotExpression;
import parser.bioscript.ast.OrExpression;
import parser.bioscript.ast.ParenthesisExpression;
import parser.bioscript.ast.PlusExpression;
import parser.bioscript.ast.PrimaryExpression;
import parser.bioscript.ast.Program;
import parser.bioscript.ast.RepeatStatement;
import parser.bioscript.ast.SplitStatement;
import parser.bioscript.ast.Statement;
import parser.bioscript.ast.Stationary;
import parser.bioscript.ast.TimesExpression;
import parser.bioscript.ast.TrueLiteral;
import parser.bioscript.ast.WhileStatement;

/**
 * Provides default methods which visit each node in the tree in depth-first order.  Your visitors
 * may extend this class.
 */
public class GJVoidDepthFirst<A> implements GJVoidVisitor<A> {
    //
    // Auto class visitors--probably don't need to be overridden.
    //
    public void visit(NodeList n, A argu) {
        int _count = 0;
        for (Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this, argu);
            _count++;
        }
    }

    public void visit(NodeListOptional n, A argu) {
        if (n.present()) {
            int _count = 0;
            for (Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
                e.nextElement().accept(this, argu);
                _count++;
            }
        }
    }

    public void visit(NodeOptional n, A argu) {
        if (n.present())
            n.node.accept(this, argu);
    }

    public void visit(NodeSequence n, A argu) {
        int _count = 0;
        for (Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this, argu);
            _count++;
        }
    }

    public void visit(NodeToken n, A argu) {
    }

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> Stationary() f1 -> Manifest() f2 -> <INSTRUCTIONS> f3 -> Instruction()
     */
    public void visit(Program n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
    }

    /**
     * f0 -> <STATIONARY> f1 -> Identifier()
     */
    public void visit(Stationary n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
    }

    /**
     * f0 -> <MANIFEST> f1 -> Identifier()
     */
    public void visit(Manifest n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
    }

    /**
     * f0 -> Instruction() | BranchStatement() | WhileStatement()
     */
    public void visit(Statement n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> MixStatement() | SplitStatement() | DrainStatement() | HeatStatement() |
     * DetectStatement() | RepeatStatement() | AssignmentStatement()
     */
    public void visit(Instruction n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> <MIX> PrimaryExpression() <WITH> PrimaryExpression() | <FOR> IntegerLiteral()
     */
    public void visit(MixStatement n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> <SPLIT> f1 -> PrimaryExpression() f2 -> <INTO> f3 -> PrimaryExpression()
     */
    public void visit(SplitStatement n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
    }

    /**
     * f0 -> <DRAIN> f1 -> PrimaryExpression()
     */
    public void visit(DrainStatement n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
    }

    /**
     * f0 -> <HEAT> PrimaryExpression() <AT> IntegerLiteral() | <FOR> IntegerLiteral()
     */
    public void visit(HeatStatement n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> <DETECT> Identifier() <ON> PrimaryExpression() | <FOR> <INTEGER_LITERAL>
     */
    public void visit(DetectStatement n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> WhileStatement()
     */
    public void visit(RepeatStatement n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> Identifier() f1 -> <ASSIGN> f2 -> Expression()
     */
    public void visit(AssignmentStatement n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> <IF> <LPAREN> Expression() <RPAREN> <LBRACE> Statement() <RBRACE> | <ELSE_IF> <LPAREN>
     * Expression() <RPAREN> <LBRACE> Statement() <RBRACE> | <ELSE> <LBRACE> Statement() <RBRACE>
     */
    public void visit(BranchStatement n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> <REPEAT> f1 -> IntegerLiteral() f2 -> <TIMES> f3 -> <LBRACE> f4 -> Statement() f5 ->
     * <RBRACE>
     */
    public void visit(WhileStatement n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
    }

    /**
     * f0 -> IntegerLiteral() | TrueLiteral() | FalseLiteral() | Identifier() |
     * ParenthesisExpression()
     */
    public void visit(PrimaryExpression n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    public void visit(IntegerLiteral n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> <TRUE>
     */
    public void visit(TrueLiteral n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> <FALSE>
     */
    public void visit(FalseLiteral n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> <IDENTIFIER>
     */
    public void visit(Identifier n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> AndExpression() | LessThanExpression() | LessThanEqualExpression() |
     * GreaterThanExpression() | GreaterThanEqualExpression() | NotEqualExpression() |
     * EqualityExpression() | OrExpression() | PlusExpression() | MinusExpression() |
     * TimesExpression() | PrimaryExpression()
     */
    public void visit(Expression n, A argu) {
        n.f0.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <AND> f2 -> PrimaryExpression()
     */
    public void visit(AndExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <LESSTHAN> f2 -> PrimaryExpression()
     */
    public void visit(LessThanExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <LESSTHANEQUAL> f2 -> PrimaryExpression()
     */
    public void visit(LessThanEqualExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <GREATERTHAN> f2 -> PrimaryExpression()
     */
    public void visit(GreaterThanExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <GREATERTHANEQUAL> f2 -> PrimaryExpression()
     */
    public void visit(GreaterThanEqualExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <NOTEQUAL> f2 -> PrimaryExpression()
     */
    public void visit(NotEqualExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <OR> f2 -> PrimaryExpression()
     */
    public void visit(EqualityExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <LESSTHAN> f2 -> PrimaryExpression()
     */
    public void visit(OrExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <ADD> f2 -> PrimaryExpression()
     */
    public void visit(PlusExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <MINUS> f2 -> PrimaryExpression()
     */
    public void visit(MinusExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> PrimaryExpression() f1 -> <MULTIPLY> f2 -> PrimaryExpression()
     */
    public void visit(TimesExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

    /**
     * f0 -> <BANG> f1 -> Expression()
     */
    public void visit(NotExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
    }

    /**
     * f0 -> <LPAREN> f1 -> Expression() f2 -> <RPAREN>
     */
    public void visit(ParenthesisExpression n, A argu) {
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
    }

}
